package com.ebc43.bc_backend.TaskManagement.ModeloAtributoEquipamento;

import com.ebc43.bc_backend.SoftDeleteRepository.IntegerIdSoftDeleteCrudRepository;

public interface ModeloAtributoEquipamentoRepository extends IntegerIdSoftDeleteCrudRepository<ModeloAtributoEquipamento, Integer>{
}